name: CICD 

on:
  push:
    branches: [ main ]


jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: multiple command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
                cd /var/www/html/Laravel8.1
                git pull origin main
                sudo apt-get install php8.1-dom php8.1-xml
                sudo apt-get install php8.1-curl
                composer install
                php artisan config:cache
